apiVersion: v1
kind: Pod
metadata:
  labels:
    app: spring-build-ci
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.6.0-debug
      imagePullPolicy: Always
      env:
        - name: container
          value: docker
      command:
        - sleep
      args:
        - 99d
      volumeMounts:
        - name: jenkins-docker-cfg
          mountPath: /kaniko/.docker

    - name: maven
      image: maven:3.9.9-eclipse-temurin-17-alpine  # Maven ve JDK içeren güncel imaj
      command:
        - cat
      tty: true
      env:
        - name: JAVA_HOME  # JAVA_HOME ortam değişkenini manuel olarak ayarlıyoruz
          value: "/opt/java/openjdk"
        - name: PATH  # PATH değişkenine JDK'yı ekliyoruz
          value: "/opt/java/openjdk/bin:/usr/local/maven/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
      volumeMounts:
        - name: m2
          mountPath: /root/.m2/
        - mountPath: /home/jenkins/agent
          name: workspace-volume

    - name: docker-tools
      image: rmkanda/docker-tools:latest
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /var/run
          name: docker-sock
        - mountPath: /tmp/trivycache/
          name: trivycache

    - name: trufflehog
      image: rmkanda/trufflehog
      command:
        - cat
      tty: true

    - name: licensefinder
      image: licensefinder/license_finder
      command:
        - cat
      tty: true

    - name: slscan
      image: shiftleft/sast-scan:v2.1.2
      imagePullPolicy: Always
      command:
        - cat
      tty: true

  volumes:
    - name: jenkins-docker-cfg
      projected:
        sources:
          - secret:
              name: regcred
              items:
                - key: .dockerconfigjson
                  path: config.json

    - name: m2
      hostPath:
        path: /tmp/.m2/

    - name: docker-sock
      hostPath:
        path: /var/run

    - name: trivycache
      hostPath:
        path: /tmp/trivycache/
